[package]
name = "kingfisher"
version = "0.1.0"
authors = ["Charlie Cummings <chc4000@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
lalrpop-util = "0.16.1"
regex = "0.2.0"

[build-dependencies]
lalrpop = "0.16.1"
